# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

principal = 20000
rot = 5
time = 10
interest = (principal*rot*time)/100
print(interest)

principal = 7800
rot = 7.7
time = 26
interest = (principal * rot * time)/100
print(interest)

year = int(input("Enter the year :"))
if(year%4==0) and (year%100!=0) or (year%400==0):
    print(year,"is a leap year")

for i in range (5,0,-1):
    print("*" * i)

a = float(input("Enter the first number:"))
b = float(input("Enter the second number:"))
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")
choice = int(input("Enter your choice:"))
if(choice == 1):
    print("Addition:",a+b)
elif(choice == 2):
    print("Subtraction:",a-b)
elif(choice == 3):
    print("Multiplication:",a*b)
elif(choice == 4):
    print("Division:",a/b)