# -*- coding: utf-8 -*-
"""Second Lab Exercises (List and Shallow and Deep Copy)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRfjCksUBc1vlvmcJsgb8Qwq62xSD2Ub
"""

list1 = [1, 2, "Python", "Program" , 15.9]
list2 = ["Amy", "Ryan", "Henry", "Emma"]
print(list1)
print(list2)
print(type(list1))
print(type(list2))

a = [1, 2, "Ram", 3.50, "Rahul", 5, 6]
b = [1, 2, "Ram", 3.50, "Rahul", 5, 6]
a == b

List = [0,1,2,3,4,5]
List[0]
List[1]
List[2]
List[3]
List[4]
List[5]
List[0:]
List[:]
List[2:4]
List[1:3]
List[4]

list = [1,2,3,4,5,6,7]
print(list[0])

print(list[1])

print(list[0:6])

print(list[1:6:2])

list = [1,2,3,4,5,6]
print(list[-1])

print(list[-3:])

print(list[-3:-1])

list[2] = 10
print(list)

list[1:3] = [89,78]
print(list)

list[-1] = 25
print(list)

list1 = [12, 14, 16, 18, 20]
I = list1 * 2
print(I)

list2 = [9, 10, 32, 54, 36]
I = list1 + list2
print(I)

list7 = [12, 14, 16, 18, 20, 23, 27, 39, 40]
len(list7)

for i in list1:
  print(i)

print(12 in list1)

print(700 in list1)

list = ["John", "Peter", "Vicky"]
for i in list:
  print(i)

I = []
n = int(input("Enter the number of elements in the list"))
for i in range (0,n):
  I.append(input("Enter the element:"))
print("printing the list items...")
for i in I:
  print(i, end = " ")

list = [0,1,2,3,4,5]
print("Printing Original List:")
for i in list:
  print(i, end = " ")
list.remove(2)
print("\nPrinting List after removing element:")
for i in list:
  print(i, end = " ")

import copy

old_list = [[1,2,3], [4,5,6], [7,8,9]]
new_list = copy.copy(old_list)

print("Old list:", old_list)
print("New list:", new_list)

import copy

old_list = [[1,1,1], [2,2,2], [3,3,3]]
new_list = copy.copy(old_list)

old_list.append([4,4,4])
print("Old list:", old_list)
print("New list:", new_list)

import copy

old_list = [[1,1,1], [2,2,2], [3,3,3]]
new_list = copy.copy(old_list)
old_list[1][1] = 'AA'
print("Old list:", old_list)
print("New list:", new_list)

import copy

old_list = [[1,1,1], [2,2,2], [3,3,3]]
new_list = copy.deepcopy(old_list)
print("Old list:", old_list)
print("New list:", new_list)

import copy
old_list = [[1,1,1], [2,2,2], [3,3,3]]
new_list = copy.deepcopy(old_list)
old_list[1][0] = 'BB'
print("Old list:", old_list)
print("New list:", new_list)